slogan: "Come to join us!!!"

theme: bootstrap
inverse: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder-open"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tag"
  - title: Members
    url: members
    intro: "All the members."
    icon: "fa fa-user"
  - title: History
    url: history
    intro: "History."
    icon: "fa fa-history"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-info-circle"
  - title: "Rss"
    url: atom.xml
    intro: "Rss Subscribe"
    icon: "fa fa-rss"

links:
  - title: "Training Website"
    url: http://train.cs.nctu.edu.tw/
    intro: "Training Website"
    icon: "fa fa-book"
  - title: "Bamboofox Facebook"
    url: https://www.facebook.com/groups/bamboofox/
    intro: "Bamboofox Facebook"
    icon: "fa fa-facebook-official"
  - title: "Bamboofox Github"
    url: https://github.com/bamboofox
    intro: "Bamboofox Github"
    icon: "fa fa-github"
  - title: "Bamboofox slack channel"
    url: https://bamboofox.herokuapp.com/
    intro: "Bamboofox slack channel"
    icon: "fa fa-slack"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

fancybox: true
favicon: img/favicon.png
duoshuo_shortname:

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false

